
# This is a special configuration file to run tests on Travis-CI via
# GitHub notifications when changes are committed.
#
# See http://travis-ci.org/ for details
language: python

before_install:
 - export GALAXY_RELEASE=release_17.05
 - export PLANEMO_RELEASE=0.47.0

install:
 - pip install planemo==$PLANEMO_RELEASE

script:
 - planemo lint ${TRAVIS_BUILD_DIR}/galaxy/normalization && planemo test --conda_auto_init --conda_auto_install --conda_dependency_resolution --galaxy_branch $GALAXY_RELEASE --no_cache_galaxy ${TRAVIS_BUILD_DIR}/galaxy/normalization
